### ISSUE TITLE
Future of  Granular conversion level measurement from Advertiser's website.

### ISSUE THREAD

**Issue by Vishnu-r-prasad** [WICG/conversion-measurement-api#112]
Hi All,

As an established measurement company, we currently capture details of online conversions on a real-time basis from the brand's conversion page using a conversion pixel. 
 
These conversion pixels share passback information which may include order id, revenue & Advertiser first party ids (at a user level granularity) on a real time basis. After reviewing the turtledove and conversion API documentation, we don’t have clarity on whether this will be allowed in Chrome in the post-cookie world. 
 
From the conversion API proposal, we understand that there is a provision to send an attribution report to a well-known location. However we understand that this will be delivered only with delay and in an aggregated manner. So information at an individual conversion level will not be available.
 
Naturally the question arises if chrome would bring in some restrictions in firing a tracking pixel or conversion pixel itself from the page.  The pixel call is essentially a third party http request to the measurement vendor’s domain.  Blocking these would be a much bigger change than just blocking of third party cookies.  Hence we wanted to reach out for clarity on this topic.
 
Please review and let me know of any perspective that you may have on this topic. In case we are bringing restrictions in firing tracking pixels and conversion pixels, it would be good to get a high level timeline if available. Please let me know if you need more information on any of these topics.

Thanks,
Vishnu

**Comment by csharrison** [comment]
I don't believe there is any proposal to block third party HTTP requests on advertisers websites. These requests are only problematic when they can be used to track the user with third party cookies. You should still be able to use these techniques to learn _unattributed_ conversion information.
