### ISSUE TITLE
Follow up question on granular conversion measurement on Advertiser websites.

### ISSUE THREAD

**Issue by Vishnu-r-prasad** [WICG/conversion-measurement-api#113]
Hi All,

@csharrison - Thank you so much for the prompt response on issue 112.  This is a follow up question to issue 112. 

For our measurement solution, We will use a hosted site tag that may capture person based identifiers such as a customer id or a hashed email address for consenting users. We will do this by firing real time third party http requests (pixel calls) to the measurement vendor’s domain with some of person based identifier that we referred to earlier. This tag will capture incoming clicks into the brand’s website from various digital publishers and search engines. We wanted to check if there are any concerns around this approach.

Please let us know if any more information is  required around this use case.

Thanks,
Vishnu

**Comment by csharrison** [comment]
I can't comment on this design, sorry. It is unrelated to the conversion measurement API.
