### ISSUE TITLE
Origin Trials with third party token and usage limits

### ISSUE THREAD

**Issue by Myrtle** [WICG/conversion-measurement-api#118]
Hi!

(Greg Truchetet from Teads here)

We are using Origin Trials (Third party) to test `Conversion Measurement` feature and what we observe is a bit disturbing. We are not sure to have fully understood how the limits applied to trials work.
This kind of question has been probably raised elsewhere but I didn't find any reference, if it's the case, sorry for the noise. :)

Our third party script, embedded on a lot of websites, write the meta tag with our trial token on every page. Then it checks that the feature is effectively enabled on the user's browser with that piece of code:
```
    function isConversionMeasurementEnabled() {
        var isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);
        return isChrome && !!document.featurePolicy && !!document.featurePolicy.features() && document.featurePolicy.features().includes('conversion-measurement');
}
```
It appears that for Chrome instances with a version greater than 86, the feature seems to be effectively activated for only 0.5%-1% of the traffic.
From what we understood by reading the Origin Trials restrictions [here](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#19-are-there-any-usage-limits-on-experimental-features), the feature should be activated for everybody, unless too many people use this feature worldwide, which is not the case when checking the [Chrome Status page](https://www.chromestatus.com/metrics/feature/popularity)

Are we missing something and this is the intended behavior?

Thanks for your help!

**Comment by johnivdel** [comment]
Hi Greg,

This repo is meant to house the proposal for an addition to the web platform. Origin Trials are a Chrome-specific feature and not part of the web platform. 

For questions directory related to Chrome's implementation, I would recommend filing a bug on chromiums bug tracker: https://bug.chromium.org. You can also reach out to https://groups.google.com/u/1/a/chromium.org/g/attribution-reporting-api-dev which is the chromium mailing list related to this API.

I would be happy to follow up on your question there. Closing this issue as it is not related to the API proposal.
