### ISSUE TITLE
Need notes for 64bit integer of attributionsourceeventid and source_event_id

### ISSUE THREAD

**Issue by shigeki** [WICG/conversion-measurement-api#123]
The current description of `attributionsourceeventid=[unsigned long long]` leads to an implementation pitfall for JavaScript developers who missed `Number.MAX_SAFE_INTEGER`. 
It should add a note that `attributionsourceeventid` can be accepted as `DOMString` and need not be handled in  Integer or BigInt.

The description of `"source_event_id: 64 bit event id set on the attribution source"` in the JSON report would also cause interoperability issues as described in https://tools.ietf.org/html/rfc8259#section-6. It should be a string type.

**Comment by csharrison** [comment]
Thanks Shigeki this is great feedback. Agree with you on both counts.

@johnivdel FYI

**Comment by johnivdel** [comment]
Resolved in the merges above.
