### ISSUE TITLE
Tweak the README to clarify API features

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#125]
* New README as an entry point that clarifies various features
* Move clicks explainer to another file
* Remove `Name probably needs bikeshedding` from the main [README](https://github.com/WICG/conversion-measurement-api/blob/main/README.md)
* Edit what's already at the beginning of the [README](https://github.com/WICG/conversion-measurement-api/blob/main/README.md), something along the lines of: `This README focuses on attribution reporting for click-through conversions, at an event's level. Extended functionality on top of this is being considered: [aggregated reports](link to AGGREGATE.md) and ...`.

LMK whether these changes sounds good; happy to open a PR.

**Comment by csharrison** [comment]
LGTM
