### ISSUE TITLE
Unspecified [Reflect] extended attribute used for <a> attributes

### ISSUE THREAD

**Issue by johnivdel** [WICG/conversion-measurement-api#133]
As noted in this [comment](https://github.com/WICG/conversion-measurement-api/pull/131/files#r614457070) on #131, [Reflect] is not defined by https://heycam.github.io/webidl/#es-extended-attributes. 

Instead this should use language like https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflect

**Comment by csharrison** [comment]
I think this is fixed?
