### ISSUE TITLE
Unrecognized feature: 'attribution-reporting'

### ISSUE THREAD

**Issue by maxcn** [WICG/conversion-measurement-api#136]
I'm trying to set up the experiment for my test integration with conversion-measurement api. 
I'm adding 
```
<iframe src="https://www.pcmprep.com/publisher.html" allow="attribution-reporting ‘src’ (https://pcmprep.com)">
...
</iframe>
```

However, I'm getting this warning 

`Unrecognized feature: 'attribution-reporting'.
`

Can you please share some advice on this? Thanks.

**Comment by johnivdel** [comment]
Hello,

This repo is meant to house a proposal for an addition to the web platform. It is not kept in sync with any browser implementations.

If you are trying to experiment in Chrome, I would recommend reaching out to the chromium.org mailing list related to this API which you can find here: https://groups.google.com/u/1/a/chromium.org/g/attribution-reporting-api-dev/.

(Here is a relevant thread https://groups.google.com/u/1/a/chromium.org/g/attribution-reporting-api-dev/c/rLanlNTBM4E)

I would be happy to follow up on your question there. Closing this issue as it is not related to the API proposal. Thanks!
