### ISSUE TITLE
Consider adding a mechanism for prioritizing across attribution triggers

### ISSUE THREAD

**Issue by johnivdel** [WICG/conversion-measurement-api#153]
The Event Attribution Reporting explainer adds a mechanism for choosing which source should be associated with a trigger via a new [attributionsourcepriority attribute](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting.md#controlling-which-attribution-source-to-trigger).

However it's not possible to prioritize among different triggers for an individual source. 

A motivating example would be something like:

Click/View Ad
Landing page conversion
Sign Up
Add to Cart
Purchase

With the [per-source report limit](https://github.com/WICG/conversion-measurement-api#triggering-attribution-multiple-times-for-the-same-source), it is impossible measure the "purchase" conversion for both navigation and event attribution sources.

We could consider introducing a priority mechanism for triggers as well, similar to what is done by PCM: https://privacycg.github.io/private-click-measurement/#optional-trigger-priority

The above example could now look like:

Click Ad
Landing page conversion - Priority 1
Sign Up  - Priority 2
Add to Cart - Priority 3
Purchase -  Priority 4

At the end of the reporting window, the browser could look at all potential reports for a given source, and choose up to N reports with the highest trigger priority to send (where N is the per-source report limit, 3 for clicked sources).

In this case, it might still be possible to not report the "purchase" if the first 3 triggers are all in the first reporting window, and the "purchase" trigger is in the second reporting window. The per-source report limit would have already been exhausted in the first window.

**Comment by shigeki** [comment]
We have observed users have more than 3 purchase conversions in our trial. 
Is the maximum still limited to 3 for each trigger priority?

**Comment by johnivdel** [comment]
> We have observed users have more than 3 purchase conversions in our trial.
Is the maximum still limited to 3 for each trigger priority?

With this approach, you would still be limited to only 3 reports. The only difference is if you had 6 conversions for a single clicked ad in a window, you would now get to choose which 3 to send reports which would allow you to recover the conversions you care the most about.

**Comment by apasel422** [comment]
Is there anything left to do here now that #158 and #193 have been merged?

**Comment by csharrison** [comment]
No I think we're good here. Closing.
