### ISSUE TITLE
View-through attribution - plausible deniability

### ISSUE THREAD

**Issue by Pl-Mrcy** [WICG/conversion-measurement-api#171]
Hi,

In the [Attribution Reporting for View-Through Measurement explainer](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md#privacy-considerations), in the context of [preventing browsing history reconstruction](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md#plausible-deniability), you state that:
> By adding noise to whether an attribute source gets triggered, a `reportingorigin` will not know with absolute certainty whether a user actually visited a site. In fact, this additional mitigation gives some local differential privacy guarantees on the data in the API.

Can you detail how this would work?

Indeed, I don't see how the added [noise on the attribution triggering event](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md#noise-on-the-attribution-triggering-event) can provide plausible deniability in this case.

**My understanding is that if the `reportingorigin` receives an attribution report from an ad printed on website A, the user must have visited website A.**

Indeed some sources (and thus websites) can be ignored for attribution (With probability `p/2`, the browser ignores any future attribution for this source) or attribution can be generated even though the user didn't really convert (With probability `p/2`, the browser immediately triggers attribution on the source with a random `event-source-trigger-data`. This report will still be sent at the end of the reporting window.) but it doesn't mention creating random attribution sources.

Am I understanding this correctly?

**Comment by johnivdel** [comment]
> Can you detail how this would work?

The browsing history reconstruction section is specific to whether a report reveals that a user visits the **attributiondestination** site, not the attribution source site. The explainer doesn't say this explicitly, and should be updated.

> My understanding is that if the reportingorigin receives an attribution report from an ad printed on website A, the user must have visited website A.

That is correct. However the report revealing that a given `sourceeventid` visited website A is not sensitive. 

The 64 bit `sourceeventid` which identifies the report is generated and set on site A. The `reportorigin` knows apriori without invoking the API that a given id visits site A. So the report itself doesn't reveal any additional information in that respect.

If the user sees an ad on site, and later visits sit B though:

The fact that a given id visited site B is not known apriori. And so noise needs to be added to the triggering event on site B to introduce plausible deniability on this end.

Does that clarify the problem?

**Comment by Pl-Mrcy** [comment]
It does thank you!
