### ISSUE TITLE
Remove `credit` occurrences? 

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#177]
@johnivdel Is credit still of use at all, given the [VTC spec](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md) and `priority`? 
If not, can we consider removing its occurrences from the spec docs? Happy to open a PR.

**Comment by apasel422** [comment]
I started work on this in #172.

**Comment by johnivdel** [comment]
For posterity, this issue is tracking upstreaming the change proposed in [this section](
https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md#controlling-which-attribution-source-to-trigger) to the click explainer.

**Comment by apasel422** [comment]
Fixed in #172.
