### ISSUE TITLE
Questions/Suggestions on conversion measurement API.

### ISSUE THREAD

**Issue by Vishnu-r-prasad** [WICG/conversion-measurement-api#185]
Hi Google team,

This is Vishnu from Nielsen Ltd (a leading measurement company). We wanted to make the following requests based on our experience with the origin trial for conversion measurement API. Please let us know the feasibility of accommodating these requests.

1.  Share day level/(hour level if possible) impression exposure data in the conversion report. We understand that the exact timestamp cannot be shared but provide day level information will help us sequence the touchpoints in order of exposure.
2.  Impression expiry - could we set it to 90 days? There are businesses where a longer lookback may make sense since the customer has a long buying cycle.
3.  Is there a way to provide an Identifier to connect the conversion report to specific conversions that may be captured on the advertiser side through a conversion pixel fire?
4.  Can we standardize the cadence at which the conversion report is send to the ad-tech server? Will it be configurable at a client level or will it be determined by Chrome.
5. Can we have multiple reporting endpoints, given that most of the advertisers will have more than one ad tech vendor?
6. Is there a way to collect touchpoint data for non-converters?
7.  Completing the feedback loop - How does the solution help in media optimization decisions? Can partners enrich the attributed data from the browser and push it to media platforms to drive optimization decisions.
8.  Is there a way to capture additional conversion information like revenue? - All conversions are not the same, some are more valuable than the others.

Thanks,
Vishnu

**Comment by appascoe** [comment]
I'm not from Google, but I can answer some of these:

3) No, you can't connect a conversion report to a specific conversion. The source event id could be used to determine that a converting user visited the publisher's site, i.e. it would enable cross-site tracking.
7) The solution can be used to determine which publishers/ads/campaigns are driving conversions more than others.
8) No. Conversion values can be very unique, and could be used to perform cross-site tracking as in point 3. Instead, you can get a rough estimate of value by using the 3-bit conversion value (which can also be used for types of conversions). It's up to you how you want to interpret those three bits.

**Comment by csharrison** [comment]
> 1. Share day level/(hour level if possible) impression exposure data in the conversion report. We understand that the exact timestamp cannot be shared but provide day level information will help us sequence the touchpoints in order of exposure.

For event-level reports, the source event ID is fine grained enough to include precise timestamps. Let us know what's missing to support this use-case.

> 2. Impression expiry - could we set it to 90 days? There are businesses where a longer lookback may make sense since the customer has a long buying cycle.

We originally chose this to limit the scope of possible tracking with the API, but if there are significant use-cases that require a longer lookback window we can consider it. Do you mind filing a separate issue just for this one, explaining the use-case in a bit more detail?

> 3. Is there a way to provide an Identifier to connect the conversion report to specific conversions that may be captured on the advertiser side through a conversion pixel fire?

No this would violate the privacy guarantees of the API.

> 4. Can we standardize the cadence at which the conversion report is send to the ad-tech server? Will it be configurable at a client level or will it be determined by Chrome.

We intend for this to be standardized, and based on a function of the source event / trigger event timing. See the wip spec for more information. https://wicg.github.io/conversion-measurement-api/#delivery-time

> 5. Can we have multiple reporting endpoints, given that most of the advertisers will have more than one ad tech vendor?

This is an open question in the API, dupe of https://github.com/WICG/conversion-measurement-api/issues/29. Feel free to comment on the use-case there, we're looking into possible ways to support this (and happy to hear any suggestions that fit within our privacy model).

> 6. Is there a way to collect touchpoint data for non-converters?

Not for this API specifically currently. This might be possible via something like the sharedStorage API though which is a bit more general of an API.
https://github.com/pythagoraskitty/shared-storage

> 7. Completing the feedback loop - How does the solution help in media optimization decisions? Can partners enrich the attributed data from the browser and push it to media platforms to drive optimization decisions.

Can you explain this use-case a bit more? I don't fully understand it.

> 8. Is there a way to capture additional conversion information like revenue? - All conversions are not the same, some are more valuable than the others.

We are exploring aggregate reports to send more detailed conversion information like purchase amount / revenue. https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md. This provides a different output than the event-level reports which are currently in Chrome's Origin Trial.

**Comment by Vishnu-r-prasad** [comment]
> > 1. Share day level/(hour level if possible) impression exposure data in the conversion report. We understand that the exact timestamp cannot be shared but provide day level information will help us sequence the touchpoints in order of exposure.
> 
> For event-level reports, the source event ID is fine grained enough to include precise timestamps. Let us know what's missing to support this use-case.
> **Nielsen Follow up :**  Typically the advertiser works with a number of DSPs and direct publisher partners. It may be a challenge to get these different DSPs and publisher partners to pass in the precise time stamps along with Media Id in a consistent format. Since the browser already has this information, would it be possible to share this information in the conversion measurement report itself.

> > 1. Impression expiry - could we set it to 90 days? There are businesses where a longer lookback may make sense since the customer has a long buying cycle.
> 
> We originally chose this to limit the scope of possible tracking with the API, but if there are significant use-cases that require a longer lookback window we can consider it. Do you mind filing a separate issue just for this one, explaining the use-case in a bit more detail?
**Nielsen Follow up:** We will raise a separate issue with details on categories like Automobile or maternity categories.
> 
> > 1. Is there a way to provide an Identifier to connect the conversion report to specific conversions that may be captured on the advertiser side through a conversion pixel fire?
> 
> No this would violate the privacy guarantees of the API.
**Nielsen Follow up:**  We understand that a fine grained user identifier will violate the privacy guarantees of the API.  We were thinking of an identifier of an intermediate level granularity say in the range of 12-16 bits for reconciling with conversion data captured on the brand/advertiser's website. We have clients which have many different conversion types on their site.  Eight discrete values are not sufficient for the range of conversion types that we have seen with our clients.
> 
> > 1. Can we standardize the cadence at which the conversion report is send to the ad-tech server? Will it be configurable at a client level or will it be determined by Chrome.
> 
> We intend for this to be standardized, and based on a function of the source event / trigger event timing. See the wip spec for more information. https://wicg.github.io/conversion-measurement-api/#delivery-time
> **Nielsen Follow up :** The delivery time logic is not clear if it would help us in set a specific time for reports or allow us to get the report with in the broad limit of two days. That's probably because this is still WIP.  Would it be possible to keep it simple and keep the time lag to 24 hours across all clients? Do we anticipate that privacy guarantees will be impacted if we keep the delivery frequency once every 24 hours for conversions in the past 24 hours?

> > 1. Can we have multiple reporting endpoints, given that most of the advertisers will have more than one ad tech vendor?
> 
> This is an open question in the API, dupe of #29. Feel free to comment on the use-case there, we're looking into possible ways to support this (and happy to hear any suggestions that fit within our privacy model).
> **Nielsen Follow up :** : Thank you for the response. We will respond on that ticket for that thread.

> > 1. Is there a way to collect touchpoint data for non-converters?
> 
> Not for this API specifically currently. This might be possible via something like the sharedStorage API though which is a bit more general of an API.
> https://github.com/pythagoraskitty/shared-storage
> **Nielsen Follow up :** : Thank you for the response. We will respond on that ticket for that 

> > 1. Completing the feedback loop - How does the solution help in media optimization decisions? Can partners enrich the attributed data from the browser and push it to media platforms to drive optimization decisions.
> 
> Can you explain this use-case a bit more? I don't fully understand it.
> **Nielsen Followup :** SA 360 external conversions upload is a good example of this usecase. SA360 essentially takes in cross media weights(credits) provided by third party vendors at click id level and uses these reports for refining bid strategies and setting conversion goals. 

> > 1. Is there a way to capture additional conversion information like revenue? - All conversions are not the same, some are more valuable than the others.
> 
> We are exploring aggregate reports to send more detailed conversion information like purchase amount / revenue. https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md. This provides a different output than the event-level reports which are currently in Chrome's Origin Trial.

We wanted to add couple of other questions too based on reading of the proposal documentation.

1. Currently, the API deals with last touch attribution. The proposal also speaks about Multi Touch attribution where the attribution report will be available with % share of attribution for each previous touchpoint. Now the typical user may use multiple devices & browsers in their customer journey towards a conversion. Nielsen has traditionally done a lot of work in this area.  How will chrome obtain that information from multiple data sources and also stitch user sessions across multiple devices to a single customer journey?
2. The API do not support view-through conversions now. Do we have any tentative timelines ( something broad like expected delivery by end of 2021)?

**Comment by maudnals** [comment]
Hi @Vishnu-r-prasad, 

> Currently, the API deals with last touch attribution. The proposal also speaks about Multi Touch attribution where the attribution report will be available with % share of attribution for each previous touchpoint. Now the typical user may use multiple devices & browsers in their customer journey towards a conversion.

This API includes proposals to address these use cases:

- Click/View in a mobile app leading to a web conversion: [App-to-web proposal](https://github.com/WICG/conversion-measurement-api/blob/main/app_to_web.md) 
- Cross-device: [Cross-device proposal](https://github.com/WICG/conversion-measurement-api/blob/main/cross_device.md)

(Feel free to ask questions on these! Ideally in a separate issue, for clarity)

You can see/follow the status of all proposals in the [README](https://github.com/WICG/conversion-measurement-api#api-features-proposals).

**Comment by maudnals** [comment]
Hi @Vishnu-r-prasad, 
I don't think we have tentative timelines to share just now⏤check out the [Status table](https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting-introduction/#status) for details.
Closing this for now - please feel free to open a new issue if you have any question.
