### ISSUE TITLE
Privacy questions

### ISSUE THREAD

**Issue by MattMenke2** [WICG/conversion-measurement-api#200]
I don't see a privacy section, and have some questions that I think need to be addressed:

"attributionreportto" isn't specified to be secure only.  I assume it's required to be?

What network partition is used for reports?  A unique one, so no network state is shared?  Do multiple reports sent at once to the same destination use the same key or different keys?

Are attribution report requests uncredentialled?

Do we respected RFC1918 to prevent remote sites from setting a local server as an attributionreportto destination?

**Comment by csharrison** [comment]
Yes, `attributionreportto` must be secure. We can update the spec and explainer.

> Do we respected RFC1918 to prevent remote sites from setting a local server as an attributionreportto destination?
I don't think we do this currently. Right now we just check that the destination is "potentially trustworthy" which includes local destinations.

> What network partition is used for reports?
I don't think this is currently spec'd but there's no reason why we shouldn't use unique keys for every report, although I don't think we do this now in Chrome's implementation (Chrome's implementation bypasses the cache for these).

**Comment by MattMenke2** [comment]
> Yes, `attributionreportto` must be secure. We can update the spec and explainer.
> 
> > Do we respected RFC1918 to prevent remote sites from setting a local server as an attributionreportto destination?
> > I don't think we do this currently. Right now we just check that the destination is "potentially trustworthy" which includes local destinations.

They're tangential issues - the issue here is we don't want to allow an attacker to talk to local resources without a CORS preflight.

> > What network partition is used for reports?
> > I don't think this is currently spec'd but there's no reason why we shouldn't use unique keys for every report, although I don't think we do this now in Chrome's implementation (Chrome's implementation bypasses the cache for these).

Bypassing the HTTP cache alone doesn't get us much - there's also sorts of other data in form of the QUIC server in use (which itself can be a unique ID, since it's a hostname), HSTS information, socket reuse, even the cert verifier's cache.

**Comment by MattMenke2** [comment]
I'm going to split this into two issues, one about the NPK, one about RFC1918.
