### ISSUE TITLE
Difference between using first-party cookies and click conversion measurement api

### ISSUE THREAD

**Issue by kzhong130** [WICG/conversion-measurement-api#204]
Hi there, from my understanding, browser locally matches the click id with conversions which happen after the click, and periodically reports to adtech platforms. I am wondering whether this is doable using first-party cookies. Both click and conversions happen within advertiser's website. Thus, if browser appends advertiser's first-party cookie, advertiser would be able to match the click to conversion activities by itself. It then reports such conversion reports to its adtech platform.

I am wondering whether the reason why conversion measurement is not done using first-party cookie is that such measurement would bring too much overhead for advertisers? Thank you!

**Comment by kzhong130** [comment]
Hi, thank you for the explanations! I got another quick question regarding the click id. Click id can be mapped to information related to publisher's website. Thus I believe this detailed information should only be visible to publisher but not to adtech platform and advertiser? I can imagine that revealing this detailed information is somewhat equivalent to publisher help with cross-site tracking via explicitly telling others the information of user on its own website. 
However, when browser reports to adtech platform, it also includes the click id. If adtech platform does not learn what is the detailed information this click id maps to, including click id in the conversion report seems not that useful?

**Comment by kzhong130** [comment]
Thank you!

**Comment by kzhong130** [comment]
> Hey, @kzhong130 thanks for raising. I think this is similar to issue #35 and issue #27. Importantly, clicks don't happen on the advertiser site, they happen on publisher sites. They only _lead to_ the advertiser site. By using some other method of cross site information transfer (like link decoration), you could use the advertiser's first party cookie to track the click ID without this API.
> 
> This proposal is about trying to satisfy a similar use-case in an even more private way than using link decoration.
> 
Hi, thank you for your previous help. I got another quick question about using link decoration compared to this API. I can imagine that when user is redirected to the advertiser's website, the url could contain parameters (e.g., conversion type) such that advertisers can learn this visit comes from a conversion. If these parameters only contain limited information about the user, it sounds to me that link decoration can also be made private. 
Do you have any thoughts on why the conversion measurement api would be more private than link decoration? Thank you!

**Comment by csharrison** [comment]
Hey @kzhong130 , I think that question is outside of the scope for this proposal. Let me point you to the PrivacyCG's work on navigational tracking (see https://github.com/privacycg/nav-tracking-mitigations). Your question is a good topic for that group.

**Comment by csharrison** [comment]
> Do you have any thoughts on why the conversion measurement api would be more private than link decoration? Thank you!

The Attribution Reporting API specifically limits the amount of data that can be transmitted via browser enforcement, which is stronger than relying on link decoration mitigations.

**Comment by kzhong130** [comment]
Thank you very much!
