### ISSUE TITLE
Add a recurrent entry to the meeting agenda for status update and developer-facing docs

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#225]
Suggestion: systematically mention developer updates in the [WICG meeting](https://github.com/WICG/conversion-measurement-api/issues/80). 
* Status update: is there a new OT, has there been a new I2P or I2Experiment?
* Are there any new (developer-facing and more) publications?
* Remind folks to join the developer mailing list

**Comment by maudnals** [comment]
Note: I don't know if these topics fit the WICG meeting since they're about browser-specific experimentation, but I think there's a lot of value in giving developer-facing updates to this group every second week.

**Comment by maudnals** [comment]
What do you think @johnivdel

**Comment by csharrison** [comment]
Sounds reasonable to me. We can include this as the first agenda bullet
