### ISSUE TITLE
Lowercase or camelcase anchor attributes?

### ISSUE THREAD

**Issue by johnwilander** [WICG/conversion-measurement-api#238]
We should align on casing for our HTML anchor attributes. Such as:
- `attributionsourceid`  or `attributionSourceId`
- `attributiondestination` or `attributionDestination`
- `attributionsourcenonce` or `attributionSourceNonce`

Here's where we are today:
- [PCM spec](https://privacycg.github.io/private-click-measurement/#linkformat) both lowercased and camelcased
- [WebKit's blog post](https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/) lowercased
- [ARA spec](https://wicg.github.io/conversion-measurement-api/#monkeypatch-anchor) both lowercased and camelcased
- [ARA explainer](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_clicks.md#attribution-source-declaration) lowercased

The HTML spec is not super clear but looks to lean toward lowercase:
- https://html.spec.whatwg.org/multipage/dom.html#attributes
- https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
- https://html.spec.whatwg.org/multipage/indices.html#attributes-3

Maybe there is a clear directive that I have missed?

**Comment by csharrison** [comment]
We took the lowercase approach as advocated by the TAG:
https://w3ctag.github.io/design-principles/#casing-rules

**Comment by johnwilander** [comment]
Thanks! So that's where that came from. I did remember us already talking about it at some point. But when I got asked about it, I could point to where. We should both fix our specs then.

**Comment by csharrison** [comment]
I don't _think_ our spec needs to change, since the IDL attributes should still be camel case (per that same TAG naming section), unless there was a spot I missed where we incorrectly camelcased an HTML attribute.

**Comment by johnwilander** [comment]
You're right. It's me who's confused on the two attributes types. I need to make an IDL change in WebKit though. Sorry for the noise.

**Comment by csharrison** [comment]
No worries! I'll close this out. Thanks TAG for non-ambiguous recommendations 😄 !
