### ISSUE TITLE
Add links to blogposts in explainers to easen onboarding

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#264]
Explainers in this repo may be the first touchpoint for folks looking to experiment with Attribution Reporting.
However, explainers are not always the most approachable guidance for newcomers⏤sometimes, high-level intro blogposts are available.
Would it make sense to link these at the top of each explainer? By adding something along these lines at the beginning of each explainer:

******
This is a technical explainer. If you're looking for a high-level intro to {e.g. Attribution Reporting with event-level reports}, head over to {link to blogpost}.
For a list of all resources on Attribution Reporting, head over to [Attribution Reporting](https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/).
******

(Note: [external documentation](https://github.com/WICG/conversion-measurement-api#external-documentation) is listed in the README but this could also be better, I'll open a separate issue for that).

@apasel422 @johnivdel @csharrison What do you think?

**Comment by csharrison** [comment]
Sounds reasonable to me. Feel free to file some PRs.
