### ISSUE TITLE
Event-level reports should indicate how noise has been applied

### ISSUE THREAD

**Issue by csharrison** [WICG/conversion-measurement-api#273]
We should consider adding fields like:

`metadata_noise_probability` or `randomized_response_probability`

This will make it easier to handle multiple implementations with different probabilities (or different experiments in the same implementation). It also signals to developers that values may be noisy.

cc @maudnals @johnivdel

**Comment by apasel422** [comment]
I'm happy to spec and implement this.

**Comment by apasel422** [comment]
Do we want to have separate fields for source event ID noise probability and trigger data noise probability?

**Comment by csharrison** [comment]
> Do we want to have separate fields for source event ID noise probability and trigger data noise probability?

Yes I think that should be fine for now.

**Comment by apasel422** [comment]
@csharrison Are we concerned about the potential for these values to be used for fingerprinting?

**Comment by csharrison** [comment]
> @csharrison Are we concerned about the potential for these values to be used for fingerprinting?

No I am not concerned. Users of the API need to know what the API is doing, so I think defending against this is going to be very challenging and we won't be exposing anything more than browser major version anyways (in majority of cases) which is being sent by default:
https://developer.chrome.com/docs/privacy-sandbox/user-agent/
