### ISSUE TITLE
Consider giving debug keys and dedup keys the same type

### ISSUE THREAD

**Issue by apasel422** [WICG/conversion-measurement-api#316]
Right now, debug keys are unsigned 64-bit integers, but dedup keys are signed 64-bit integers. I'm not sure there's a reason that the latter is signed.

**Comment by johnivdel** [comment]
I think consistency with source_event_id is also a motivating factor. Deduplicating on a single unique event seems like a reasonable use-case, and for soruce_event_id we have decided unsigned ints are the best representation there.
