### ISSUE TITLE
Move reporting endpoint to be origin based

### ISSUE THREAD

**Issue by csharrison** [WICG/conversion-measurement-api#34]
Having this endpoint be domain based provides very little concrete benefit, since we enforce that the conversion registration needs to land on precisely on the URL `https://<reportingdomain>/.well-known/register-conversion?...` to stick (i.e. it can't be a sub domain).

Therefore to provide more flexibility, I propose making the following changes:

- Make the reporting endpoint an origin
- Enforce that the conversion registration is the result of a same-domain redirect

@johnivdel what do you think?

**Comment by johnivdel** [comment]
These changes sound good to me.

It's worth noting that having this be an origin more easily allows the mechanism discussed on #32, involving the use of different reporting domains to selectively convert different classes of impressions.

**Comment by csharrison** [comment]
Indeed, in that it allows using subdomains rather than registering new domains. However, as https://github.com/sleevi/psl-problems notes, adding yourself to the PSL is very easy so even with the existing design, you can do this trick pretty easily by claiming all your subdomains are operated by different entities. In any case I think if this turns into a vector for abuse, there are additional ways the browser could intervene.

The use case I am thinking of here is ad-tech companies that want to service different advertisers on different origins, or process reports differently with multiple services running under the same domain.
