### ISSUE TITLE
Clarify reporting limitations

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/conversion-measurement-api#345]
Hello,

In the [reporting limits](https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#reporting-origin-limits) section of the event API explainer, there is something which I don't understand. 
The number of reporting origins is capped at **100** (counted per source registration) per <source site, destination site> pair per 30 days.
Meanwhile, the number of reporting origins is capped at **10** per <source site, destination site> pair per 30 days.

It seems to me that the first limit is not useful as unmatched (or untriggered) sources are never reported and hence useless for reporting origins.

Maybe I missed something, please correct me in this case!
EDIT: corrected the mistake highlighted by @maudnals

**Comment by maudnals** [comment]
Hi @alois-bissuel,

> Meanwhile, the number of reports is capped at 10 per <source site, destination site> pair per 30 days.

What the proposal suggest to cap at **10** (per 30 days) is not the number of reports; it's the number of **reporting origins** (typically adtechs) that can send reports per <publisher site, advertiser site> pair. 
Is this what you're referring to?

**Comment by alois-bissuel** [comment]
Yes, this is the limitation I am referring to, my bad.
