### ISSUE TITLE
Origin Trial?

### ISSUE THREAD

**Issue by kweizetaglobal** [WICG/conversion-measurement-api#367]
Is the Origin Trial (OT) complete? (https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline) indicates the Attribution API OT started and has not closed. However, the 
OT sign up link indicates the OT is closed, as per (https://developer.chrome.com/origintrials/#/view_trial/3411476717733150721/)

**Comment by johnivdel** [comment]
The links above are for a Chrome-specific feature. For questions directory related to Chrome's implementation, I would recommend looking at/reaching out to https://groups.google.com/u/1/a/chromium.org/g/attribution-reporting-api-dev which is the chromium.org mailing list related to this API.

I would be happy to follow up on your question there. Closing this issue as it is not related to the API proposal / web platform.
