### ISSUE TITLE
Data Encoding For source_event_id

### ISSUE THREAD

**Issue by ley8** [WICG/conversion-measurement-api#371]
As stated in [Data Encoding](https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#data-encoding) section, it seems a browser can set non-predefined modulus on source_event_id. It's not clear what the range of modulus (max_value) is.  Will this value be reasonable to avoid collision for a normal user X site in 30 days? 

Also I assume the source_event_id after mod is combined with attribution source as internal state lookup key so a malicious site couldn't cause cross-site id collision by creating high # of source_event_ids?

**Comment by johnivdel** [comment]
> As stated in [Data Encoding](https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#data-encoding) section, it seems a browser can set non-predefined modulus on source_event_id. It's not clear what the range of modulus (max_value) is. Will this value be reasonable to avoid collision for a normal user X site in 30 days?

The explainer does not make this very clear, but the proposal recommends a value of 64 bits per https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#data-limits-and-noise which is large enough to avoid collision. 

The data encoding section is pointing out that in theory a browser may choose a different limit here, and this modulus approach is one way to achieve interoperability. As you point out, if a value is chosen which is not unique with a user X site X 30 days, the reports will be less useful from a modeling perspective.

> Also I assume the source_event_id after mod is combined with attribution source as internal state lookup key so a malicious site couldn't cause cross-site id collision by creating high # of source_event_ids?

I believe this is correct. The value of source_event_id (and its maximum size) should have no affect on the browser performing attribution and sending reports.

**Comment by apasel422** [comment]
> Also I assume the source_event_id after mod is combined with attribution source as internal state lookup key so a malicious site couldn't cause cross-site id collision by creating high # of source_event_ids?

Yes, `source_event_id` is not used as an internal key by the browser.
