### ISSUE TITLE
Conversion registration should be gated on a Feature Policy

### ISSUE THREAD

**Issue by johnivdel** [WICG/conversion-measurement-api#42]
Currently only impression declaration is gated on a feature policy being enabled. This allows sites to prevent third-parties from using the API if they desire.

We should make this same restriction on the conversion side, this way the conversion site also has control over preventing third-parties from using the API.

**Comment by csharrison** [comment]
I think in particular here, by doing this we can remove the main frame restriction on iframes, because we can migrate to a permission model.
