### ISSUE TITLE
Support conversion deduplication in Event-Level API

### ISSUE THREAD

**Issue by johnivdel** [WICG/conversion-measurement-api#48]
Currently, the aggregate API explainer proposes a new attribute, [`local-dedup-key`](https://github.com/WICG/conversion-measurement-api/blob/master/AGGREGATE.md#many-per-click--once-per-click), for conversion registration that allows the reporting origin to deduplicate conversions client side.

In the Event-level API it is already possible for the reporting origin to do server side de-duping by looking at conversion-metadata, assuming that those bits are used in a way that de-duping is possible.

It may be possible to support this attribute in the event-level API, as it should not introduce any new information leakage on the conversion side. This would allow for a unified way of de-duping conversions client side, as well as allow the conversion metadata to be used for things other than de-duping.

**Comment by apasel422** [comment]
Raising the question of doing cross-impression deduping, rather than per-impression deduping. Is the former more valuable than the latter?

**Comment by johnivdel** [comment]
To add a bit more context, consider the example:

impression 1
conversion 1 dedup=1
impression 1
conversion 2 dedup=1
impression 2
conversion 3 dedup=1

Cross-impression deduping would result in one report: [<impression 1, conversion 1>]
Per-impression deduping would result in two reports: [<impression 1, conversion 1>, <impression 2, conversion 3>]

One of the issues with cross-impression deduping is the complexity of lifetimes. After a dedup-key is set, how long should the browser wait before forgetting about this key?

In the per-impression case, the lifetime is explicitly bound to the impression.

In the cross-impression case, this is unclear. Should it be a fixed number of days? Should it be longer? Eventually the browser will need to stop checking against the key.

Overall the per-impression case seems simpler to reason about, and doesn't require the browser doing it's own management "behind the scenes".
