### ISSUE TITLE
respect example domain

### ISSUE THREAD

**Issue by Jxck** [WICG/conversion-measurement-api#50]
there are lot of domain in the explainer for help to understand.
but it can be a real domain even if there are no owner now.

- toaster.com
- ad-tech.com

etc
for this purpose, Example domains are exists.

- <https://tools.ietf.org/html/rfc2606 >

.example can be free & recommended to use in documentation like expainer.
it seems better to respect them.

(same as https://github.com/WICG/trust-token-api/issues/24)

**Comment by maudnals** [comment]
@johnivdel Is this something you're planning on changing in the explainers?

**Comment by maudnals** [comment]
Fixed in #161
