### ISSUE TITLE
Attributes naming and terms

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#57]
A few terms and attribute names in the API and explainer may (or may not) create confusion.

1. "Impression" (term) refers to both the tag and the event. 

2. `impression...` (attribute) may refer to both click and view in this spec. But in adtech lingo, "impression" usually means "view" as opposed to "click" (see the [definition from the IAB](https://www.iab.com/insights/glossary-of-terminology/#index-9): "Each time an advertisement loads onto a user’s screen, the ad server may count that loading as one impression" and [this one](https://clearcode.cc/glossary/impression/)). This means that `impression...` does not reflect the duality of "click or view" and that the API may be misunderstood as a view-through measurement API only.

3. Both the terms "data" and "metadata" are used; similarly, we have `impression-data` and `conversion-metadata` attributes. This may be hard to remember and confusing for API users; it's not necessarily clear why one qualifies as data while the other as metadata. **Note:** I think the API already reflects this, and this is just about updating the explainer.

**=> Ideas to solve these / proposals:**

1. In the explainer, clarify with "... tag" when referring to the tag - and stick to "..." when referring to the event.

2. Rename `impression` (@johnivdel suggests: "naming needs to be agnostic to click, since some API variants may support viewed impressions"). 
Ideas: 
- `impression` -> `event`, `conversion` -> `conversion` // may be confusing to differentiate between `eventdata` and `conversiondata`.
- `impression` -> `impact`, `conversion` -> `conversion`
- (by @johnivdel ) `measurement-data`
- (by @johnivdel ) `click-measurement-data` / `view-measurement-data`
- (by @johnivdel ) `link-measurement-data`
- `click-data` / `view-data`
- `click-event-data` / `view-event-data`
- `click-view-event-data`
- `click-view-data`
- `impression` -> `trigger`, `conversion` -> `conversion`. `trigger-data`, `conversion-data`.
- `impression` -> `trigger-event`, `conversion` -> `conversion`. `trigger-event-data`, `conversion-data`.

3. Unify: use data everywhere, both as terms and in the attributes.

**Comment by maudnals** [comment]
@johnivdel @csharrison

**Comment by csharrison** [comment]
Chatted about this in person, and one way I think one way to think about this is:

1. Using this API, all ad impressions (even in the view sense) would be annotated with data about itself
2. All subsequent uses of that data for attribution / reporting is scoped at something more like "eligible impressions" i.e. ones that are clicked in the current API.

In this framing "impression data" might be OK to keep around, as long as we don't call things downstream (like the click, or the data stored in the browser) as the impression data, since it's dealing with a subset of impressions. As a first idea, maybe we could have:

- "impression-data" --> data on each impression
- "attributable-impression-data" --> the subset of impression data that may be used later for attribution

**Comment by csharrison** [comment]
Sorry, to respond to more points:

> 1. "Impression" (term) refers to both the tag and the event.

Yes I think we should be using this to refer to the tag only and not the event (which could be a view, click, etc). That event should be called something else (e.g. the event which marks the impression eligible for attributability)

> 3. Both the terms "data" and "metadata" are used; similarly, we have impression-data and conversion-metadata attributes. This may be hard to remember and confusing for API users; it's not necessarily clear why one qualifies as data while the other as metadata. Note: I think the API already reflects this, and this is just about updating the explainer.

Yes let's just stick with "data".

**Comment by maudnals** [comment]
Great, thank you.
3. is solved then, I'll open a dedicated PR for this.

---
This leaves us with "impression" designating several entities (1.) and meaning "view" in the ads space (2.).
With your feedback and our chat, here's the completed picture:

### 1. Several entities are designated by the same term

As of now, "impression" in the explainer and the API is used:
- To designate he HTML `<a>` tag, be it before or after a click or view has happened
- To designate the event of the user clicking or viewing the ad
- To designate a piece of data stored in the browser _once a click or view has happened_ (= "attributable impression" concept @csharrison proposed)
- In the HTML attributes `impression-data` and `impression-expiry`
Note: This list is a base to clarify; a distinct term for each of these may not be needed. 

[Opinion: from a web development and event-level API newcomer perspective, I think there's value in making theses entity types clear ("[...] tag", "[...] event").]

### 2. The impression term itself designates "views" in the ads space

**In theory, definition:**
"An online advertisement impression is a single appearance of an advertisement on a web page" (source: [IAB](https://www.iab.com/insights/glossary-of-terminology/#index-9)).

**In theory, uses of this term in the wild:**
Note: not all of these would map to the event-level API, but this illustrate how the term is used in the ads space.
  - Google Ads: "An impression is counted each time your ad is shown" (source: [Google Ads Help](https://support.google.com/google-ads/answer/6320?hl=en#gbwa:~:text=An%20impression%20is%20counted%20each%20time%20your%20ad%20is%20shown)). "Cost-per-thousand impressions (CPM): A way to bid where you pay per one thousand views (impressions)" (source: [Google Ads Help](https://support.google.com/google-ads/answer/6310?hl=en))
  - Microsoft Ads: "Impressions are the number of times an ad has been displayed on search results pages" (source: [Microsoft Ads Help](https://help.ads.microsoft.com/apex/index/3/en-us/50860#exp55:~:text=Impressions%20are%20the%20number%20of%20times%20an%20ad%20has%20been%20displayed%20on%20search%20results%20pages.))
  - iOS: "A viewable impression is logged on Workbench when Apple has received confirmation from iOS that
100 percent of the banner was fully displayed on-screen" (source: [Apple's Ad Guide for Publishers, May 2020](https://developer.apple.com/news-publisher/News-Publisher-Advertising-Guide.pdf))

Note: this could be partly mitigated by the solutions we come up for 1. - for example, if a renaming is decided on and reduces occurrences of the term "impression" in contexts where it may be misunderstood.

**Comment by csharrison** [comment]
Accidentally closed by the PR. Re-opening

**Comment by maudnals** [comment]
After gathering ideas and feedback, together with @csharrison, @johnivdel - with input from @michaelkleber, @domenic
and folks I couldn't find a Gh handle for, here is a shortlist of new names ideas.

_Note that some of these new name ideas address the original concern mentioned in this issue (`impression` may be confusing). Other were suggested organically during the renaming brainstorming to address other goals - for example, an API name that is less tied to a use case and reflects more closely what the API does._


[API Name] | Conversion Measurement Event-level API | Attribution reporting API
-- | -- | --
[Term] HTML <a> tag, before or after a click/view has happened | impression | Attribution anchor
[Term] Event of the user clicking or viewing the ad | impression | click or view
[HTML attribute] Data/id tied to the <a> tag | `impressiondata` | `attributionid`
[HTML attribute] Origin | `conversiondestination` | `attributeon`
[HTML attribute] Expiry | `impressionexpiry` | `attributionexpiry`
[HTML attribute] Where to send the report to | `reportingorigin` | `attributionreportto`
[Term] Piece of data stored in the browser once a click or view has happened; this piece of data includes, but is not limited to, impression-data. | impression | attributable click or view
[Term] Event of the user converting / that triggers an attribution request | conversion | attribution trigger
[Term] Data attached to a conversion | conversion data | attribution trigger data
[Term] Piece of data stored in the browser once a click or view has converted; this piece of data includes, but is not limited to, conversion data.= "linked data" conversion+impression | conversion | attributed click or view
[Term] Report | conversion report | attribution report
[`Paths and query parameters`] Path to trigger a conversion eventQuery parameter for the data attached to a conversion | .well-known/register-conversion?conversion-data=<data> |  
[`Path`] Path where report is sent | .well-known/register-conversion?impression-data=x&conversion-data=y&attribution-credit=z |

**Comment by csharrison** [comment]
@johnwilander I mentioned in the last f2f that we were brainstorming some new names and terms for the API. Would you mind taking a look and sharing your thoughts?

I think the new names avoid some pitfalls of ambiguous technical ads terms on our side (impression & conversion) and also avoids embedding a use case (ads measurement) into the API name in favor of making the API more generic to the underlying primitive (attributing two events on different sites).

**Comment by johnivdel** [comment]
To follow up on the above regarding the web exposed names specifically. Integrating some of the discussion on [privacycg/private-click-measurement#56](https://github.com/privacycg/private-click-measurement/issues/56, here is a finalized set of proposed name change:

**HTML**
- impressiondata -> attributionsourceid
- conversiondestination -> attributeto
- impressionexpiry -> attributionexpiry
- reportingorigin -> attributionreportto

**URLS**
- /.well-known/register-conversion (conversion GET redirect url) -> /.well-known/trigger-attribution
- /.well-known/register-conversion (conversion report post url) -> /.well-known/report-attribution

**Query params**
- conversion-data (query param) -> data

The report param names would follow the results of the discussions on privacycg/private-click-measurement#30[](https://github.com/privacycg/private-click-measurement/issues/30#issuecomment-730598490), which I have copied here for brevity:

{
  "source_engagement_type" : "click",
  "**source_site**" : "social.example",
  "**source_id**" : 40,
  "**attributed_on_site**" : "shop.example",
  "**trigger_data**" : 3,
  "version": 1
}

**Comment by abebis** [comment]
> conversiondestination -> attributeto

attributeon :)

**Comment by maudnals** [comment]
Thank you John! 
For reference, the issues in question:
https://github.com/privacycg/private-click-measurement/issues/59
https://github.com/privacycg/private-click-measurement/issues/56
https://github.com/privacycg/private-click-measurement/issues/30

**Comment by maudnals** [comment]
Renaming is complete, closing this issue.
