### ISSUE TITLE
Consider removing `0x` prefixing for hex values from the explainer

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#61]
From @johnivdel: Both conversion and impression data are hex, but `0x` prefixes are not used by the API (and will actually cause parsing to **fail**) .

=> Suggestion: remove `0x` prefixing for hex values from the explainer, to avoid confusing API users?

**Comment by csharrison** [comment]
Yes let's do this. I can file a quick PR

**Comment by maudnals** [comment]
This has been fixed
