### ISSUE TITLE
Remove use of [Reflect] from WebIDL

### ISSUE THREAD

**Issue by jyasskin** [WICG/conversion-measurement-api#67]
https://wicg.github.io/conversion-measurement-api/#html-monkeypatches uses the [Reflect] extended attribute, which isn't standardized. https://github.com/whatwg/html/issues/3238 tracks defining it, but it's not done yet.

Instead, imitate https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element:reflect by saying things like "The IDL attribute conversiondestination, impressiondata, ... must reflect the respective content attributes of the same name."

**Comment by johnivdel** [comment]
The was resolved in #140
