### ISSUE TITLE
Change `eTLD+1` to `origin` in the README for `conversiondestination`

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#88]
`conversiondestination="[eTLD+1]"` isn't correct in the current version of the API (see #87).
Should we update this?

**Comment by csharrison** [comment]
I think the explainer should be normative and not reflect bugs in any implementation including Chrome, but we can include a note that right now Chrome implements this as per-origin

**Comment by maudnals** [comment]
Closing since [fix](https://bugs.chromium.org/p/chromium/issues/detail?id=1131624) is on the way
