### ISSUE TITLE
Reports sending: handling errors

### ISSUE THREAD

**Issue by maudnals** [WICG/conversion-measurement-api#90]
_(I suspect this is question is a browser implementation one, so this repo may not be the right place. I was asked the following:)_
Regardless of the delays, will there be a mechanism to ensure that conversion reports are received no matter what? If the request made by the browser to send the report to `reportingorigin` fails, will there be retries?

**Comment by johnivdel** [comment]
I'm not sure that this has to be specific to a browser implementations. In Chrome's current implementation, there is not retry mechanism.

However, other APIs do spec the retry mechanism. For example, the Reporting API draft spec specifies the [retry mechanism](https://www.w3.org/TR/reporting/#dom-endpoint-retry_after), but leaves constant values to the discretion of browsers.

I think sending retries for failed reports is useful for developers, and is in line with other web APIs.

**Comment by maudnals** [comment]
Relates to / Duplicate of #160.
Closing.
