### ISSUE TITLE
3 bits limitation

### ISSUE THREAD

**Issue by iab-france** [WICG/conversion-measurement-api#94]
Hi,
I am writing on behalf of the dedicated IAB France taskforce working on sandbox. On the conversion measurement API, we are having issue with the limitation on 3 bits.

3 bits conversion seems unusable when looking at existing use cases. DSP will run hundred of thousands conversion pixels, each having a unique id to allow pixel identification at reporting time. Advertisers also usually want to know conversion information, such as  product pricing, product category, product id. All those information can’t be reported with only 3 bits information.

Then, we do not understand why is it so important to have these kind of limitations and how does it benefits from a privacy point of view.

**Comment by csharrison** [comment]
We understand that 3 bits of information is not enough to support all use-cases. We are hoping to support some of those using the proposed [aggregate reports](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md) in the API.

In terms of privacy, the goal of the API is to make cross site information channels hard to abuse (e.g. to join identifiers across sites). You can see why increasing the 3-bits to 64 bits would allow something like site-to-site cookie joining to be possible which is against our high level privacy threat model.
