### ISSUE TITLE
How & when?

### ISSUE THREAD

**Issue by iab-france** [WICG/conversion-measurement-api#95]
Hi,
I am writing on behalf of the dedicated IAB France taskforce working on sandbox, we don't understand how and wehn you can get the data into the browser for the agregated reporting?

**Comment by xhudik** [comment]
I'm newbie here, but my understanding is there is a conversion script on a web page. Once the conversion is achieved., the script will notify Chrome. And this is a process of getting data to the browser

**Comment by csharrison** [comment]
Hey folks, please take a look at the updated documentation we recently published. Let me know if this clarifies.
https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md

**Comment by csharrison** [comment]
Closing for now but please open targeted issues if there is any further confusion.
